please-build/puku

generate/import.go
generate/import_test.go

It's common practice to check in generated files, so we're going to have to solve this a different way. We currently ignore symlinks so for the default behavior of `plz generate`, which is to link using symlinks, puku will correctly ignore these files.

Include generated files

---

generate/generate.go
generate/generate_test.go

We have the sources we find in the package directory, and in #55 we introduced the concept of having another mapping for the sources for a given target. This second map includes generated sources. We accidentally passed the wrong set downstream which can result in nil pointers.

Fix issue with NPE when trying to look up target sources

---

generate/generate.go
graph/graph.go
graph/graph_test.go
licences/licences.go
migrate/migrate.go

Before:
```
$ puku fmt vault/xpl/transactions/streaming/orchestrator/...
$ git diff --name-only
common/go/grpc/BUILD
vault/xpl/transactions/streaming/orchestrator/executors/BUILD
```
After:
```
$ puku fmt vault/xpl/transactions/streaming/orchestrator/...
$ git diff --name-only
vault/xpl/transactions/streaming/orchestrator/executors/BUILD
```

Only format paths that were originally passed in

---

graph/BUILD
graph/graph.go
logging/BUILD

There are some dodgy rule in our codebase that don't have a `name` arg. This confuses puku because it can't find the rule expression for that target. This logs a warning but still does the potentially useful bit of updating/generating the libs we're formatting.

Downgrade visibility error to a warning

---

generate/deps.go
generate/deps_test.go

Use configuration of the local dependency not the configuration of the source target.
Before this PR, when using a global `puku.json` that contains a `excludeBuiltinKinds`, this excluded kind is used during the dependency discovery leading to not take into account the `puku.json` file of the dependency folder.
For example, I have `/puku.json` with `"excludeBuiltinKinds": {"proto_library"}` and a `/foo/puku.json` that revert it with `  "libKinds": { "proto_library": { "nonGoSources": true } }`. If a `/bar` module depend on the `proto_libray()` of `foo`, then puku print `WARNING couldn't resolve...` and did not add the dependency in `/bar`.

Use config of dependency folder during local dependency discovery

---

migrate/migrate.go

We used to append them to the end of the file, which makes code review hard. This replaces the go_module rules in place so it's easier to review.

Make migrate insert rules where the go_modules are

---

cmd/puku/puku.go
migrate/migrate.go
migrate/migrate_test.go
please/query_config.go
sync/sync.go

Previously you had to do a `go get` on the module you wanted to migrate before `puku migrate`ing it. With this change we execute the `go get` internally.
It's done differently depending on how many modules are passed into `puku migrate`. If there are no modules passed in, all discovered `go_module`s are migrated, and we pass them all to `go get` to let `go` resolve the correct versions. If multiple modules are passed in, we again pass all of them to `go get`, and then transitively migrate them one by one. If exactly one module is passed in, we'll look to see if there's a `go_module` with a version tag for that module already in the build file, and if there is, we'll `go get` the module at that version, and then migrate it and its dependencies.

Do `go get` as part of module migration

---

cmd/puku/puku.go
generate/deps.go
generate/deps_test.go
generate/generate.go
generate/generate_test.go
migrate/migrate.go
migrate/migrate_test.go
proxy/BUILD
sync/BUILD
sync/integration/syncmod/BUILD
sync/integration/syncmod/sync_mod_test.go
sync/sync.go
watch/watch.go

This moves some things around to reduce leakage of package-specific runtime information that is never shared. It's now all contained within structs that are local to their respective packages, and the way to get at the core functionality of each package is through the functions `generate.Update()`, `migrate.Migrate()`, and `sync.Sync()`.

Refactor migrate, sync, and generate packages

---

generate/generate.go
generate/generate_test.go
graph/graph.go
graph/graph_test.go
please/query_config.go

Previously we would add visibility for a label which is in the experimental dirs (set in the please config). Please permits experimental labels to access all labels in the rest of the graph without needing visibility to be set so this was adding unnecessary noise on a puku fmt.

Don't ensure visibility for experimental labels

---

config/config.go
config/config_test.go
generate/generate.go

Previously we were just looking at the current directories stop. Now we look up the config paths to the root to ensure we don't have a stop true in one of them.

recursively look at base configs to determine if we should stop

---

.github/workflows/golangci-lint.yml
cmd/puku/puku.go
generate/generate.go
graph/graph.go
graph/graph_test.go
licences/licences.go
licences/licences_test.go
migrate/migrate.go
migrate/migrate_test.go
sync/integration/syncmod/sync_mod_test.go
sync/sync.go
watch/watch.go

previously we would print the contents of the updated formatted build files to stdout as text. It can be useful for linters to be able to output as json for easier parsing especially when multiple files are updated at once.

can specify the output format as text or json

---

ChangeLog
eval/BUILD
eval/eval.go
eval/eval_test.go
glob/glob.go
glob/glob_test.go

Previously binary expressions were ignored by puku. This meant statements like `glob(["*_test.go"]) + ["file.go"]` would not be evaluated properly. causing unnecessary churn and issues when evaluating if all sources were assigned.

supporting binary expressions for srcs

---

eval/eval.go
eval/eval_test.go
glob/glob.go
glob/glob_test.go

Since we can't do `["a", "b"] - ["a"]` the only operation that makes sense is + anyway so only handle that

simplify binary expression evaluation

---

edit/edit.go
generate/generate.go
logging/BUILD
sync/BUILD
sync/integration/syncmod/BUILD
sync/integration/syncmod/sync_mod_test.go
sync/integration/syncmod/test_repo/go.mod
sync/sync.go

We're thinking it would be useful to have a label on the build rule if a go module is pinned with a replace directive.
This way we can see which versions are pinned when checking through which need updating and such

Add a label to the build rule if a go repo target has a replace directive in go.mod

---

edit/edit.go
sync/integration/syncmod/sync_mod_test.go
sync/integration/syncmod/test_repo/third_party/go/BUILD_FILE
sync/sync.go

The previous PR I made, #114, added `go_replace_directive` labels to all go_repo rules which had a replace directive in the go.mod file. But it did not remove that label from any rules which do not have a go.mod replace directive.
(Also, it added go_replace_directive labels to any new rules without replace directives, whoops)
Extended tests, and fixed functionality to ensure that go_replace_directive labels are removed from all rules which lack replace directives in the go.mod file

Remove replace directive labels when not needed

---

edit/BUILD
edit/build_target_test.go
edit/build_targets.go
edit/rule.go
generate/deps.go
generate/deps_test.go
generate/generate.go
generate/generate_test.go
kinds/BUILD
migrate/migrate.go
plugins/BUILD

This stuff probably doesn't really make sense in the generate package. They're just useful helpers. 
If we introduce other languages, these should be in a common place that each language updater can use them.

Move the rule helpers out into the edit package

---

.github/workflows/puku.yaml

actions/upload-artifact@v2 is deprecated and workflows aren't able to use it any more.

Use actions/upload-artifact@v4 in GHA workflow

---

.github/workflows/puku.yaml
.plzconfig.release
knownimports/BUILD
knownimports/known_imports.go
package/BUILD
package/architectures.build_defs
third_party/go/BUILD

We can use the stdlib instead to find the known packages, and we don't need to maintain the build defs file for the architectures because each stdlib will just get built on demand for that arch.
Have manually checked the known packages file against master, both hash the same (`7dc0e2400b15abcd5992f01125168ecf44b303cebe707cf447f641d783218d60`, not that anyone cares)

Simplify toolchain setup

---

graph/graph.go
graph/graph_test.go

`//...` specifies any build target within the main repo. Take this into account when determining whether a target is visible to another target when the former uses it as a visibility identifier.
Fixes #138.

Correctly handle `//...` as a visibility identifier

---

graph/graph.go
graph/graph_test.go

`isSubpackage` panics when there are more components in the base package name than the target package name. Explicitly compare the package names component-wise to avoid this.

Correctly compute visibility of target given a child package wildcard
